// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archived_file_versions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type CreateArchivedFileVersionsBulkParams struct {
	ID                uuid.UUID `json:"id"`
	ArchivedFileID    uuid.UUID `json:"archived_file_id"`
	OriginalVersionID uuid.UUID `json:"original_version_id"`
	VersionNumber     int32     `json:"version_number"`
	MinioVersionID    string    `json:"minio_version_id"`
	Size              int64     `json:"size"`
	Checksum          string    `json:"checksum"`
	UploadedBy        uuid.UUID `json:"uploaded_by"`
	CreatedAt         time.Time `json:"created_at"`
}

const deleteArchivedFileVersionsByArchivedFileID = `-- name: DeleteArchivedFileVersionsByArchivedFileID :exec
DELETE FROM archived_file_versions WHERE archived_file_id = $1
`

func (q *Queries) DeleteArchivedFileVersionsByArchivedFileID(ctx context.Context, archivedFileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchivedFileVersionsByArchivedFileID, archivedFileID)
	return err
}

const listArchivedFileVersionsByArchivedFileID = `-- name: ListArchivedFileVersionsByArchivedFileID :many
SELECT id, archived_file_id, original_version_id, version_number, minio_version_id, size, checksum, uploaded_by, created_at FROM archived_file_versions
WHERE archived_file_id = $1
ORDER BY version_number DESC
`

func (q *Queries) ListArchivedFileVersionsByArchivedFileID(ctx context.Context, archivedFileID uuid.UUID) ([]ArchivedFileVersion, error) {
	rows, err := q.db.Query(ctx, listArchivedFileVersionsByArchivedFileID, archivedFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivedFileVersion{}
	for rows.Next() {
		var i ArchivedFileVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArchivedFileID,
			&i.OriginalVersionID,
			&i.VersionNumber,
			&i.MinioVersionID,
			&i.Size,
			&i.Checksum,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
