// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_paths.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteFolderPathsByDescendant = `-- name: DeleteFolderPathsByDescendant :exec
DELETE FROM folder_paths WHERE descendant_id = $1
`

func (q *Queries) DeleteFolderPathsByDescendant(ctx context.Context, descendantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolderPathsByDescendant, descendantID)
	return err
}

const deleteSubtreePaths = `-- name: DeleteSubtreePaths :exec
DELETE FROM folder_paths fp_outer
WHERE fp_outer.descendant_id IN (
    SELECT fp_inner.descendant_id FROM folder_paths fp_inner WHERE fp_inner.ancestor_id = $1
)
`

func (q *Queries) DeleteSubtreePaths(ctx context.Context, ancestorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubtreePaths, ancestorID)
	return err
}

const getAncestorIDs = `-- name: GetAncestorIDs :many
SELECT ancestor_id FROM folder_paths
WHERE descendant_id = $1 AND path_length > 0
ORDER BY path_length ASC
`

func (q *Queries) GetAncestorIDs(ctx context.Context, descendantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAncestorIDs, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var ancestor_id uuid.UUID
		if err := rows.Scan(&ancestor_id); err != nil {
			return nil, err
		}
		items = append(items, ancestor_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAncestorPaths = `-- name: GetAncestorPaths :many
SELECT ancestor_id, descendant_id, path_length, created_at FROM folder_paths
WHERE descendant_id = $1 AND path_length > 0
ORDER BY path_length ASC
`

// Excludes self-reference (path_length = 0) to avoid duplicate when creating new folder
func (q *Queries) GetAncestorPaths(ctx context.Context, descendantID uuid.UUID) ([]FolderPath, error) {
	rows, err := q.db.Query(ctx, getAncestorPaths, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FolderPath{}
	for rows.Next() {
		var i FolderPath
		if err := rows.Scan(
			&i.AncestorID,
			&i.DescendantID,
			&i.PathLength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescendantIDs = `-- name: GetDescendantIDs :many
SELECT descendant_id FROM folder_paths
WHERE ancestor_id = $1 AND path_length > 0
ORDER BY path_length ASC
`

func (q *Queries) GetDescendantIDs(ctx context.Context, ancestorID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getDescendantIDs, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var descendant_id uuid.UUID
		if err := rows.Scan(&descendant_id); err != nil {
			return nil, err
		}
		items = append(items, descendant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescendantsWithDepth = `-- name: GetDescendantsWithDepth :many
SELECT descendant_id, path_length FROM folder_paths
WHERE ancestor_id = $1 AND path_length > 0
`

type GetDescendantsWithDepthRow struct {
	DescendantID uuid.UUID `json:"descendant_id"`
	PathLength   int32     `json:"path_length"`
}

func (q *Queries) GetDescendantsWithDepth(ctx context.Context, ancestorID uuid.UUID) ([]GetDescendantsWithDepthRow, error) {
	rows, err := q.db.Query(ctx, getDescendantsWithDepth, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDescendantsWithDepthRow{}
	for rows.Next() {
		var i GetDescendantsWithDepthRow
		if err := rows.Scan(&i.DescendantID, &i.PathLength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSelfAndDescendantIDs = `-- name: GetSelfAndDescendantIDs :many
SELECT descendant_id FROM folder_paths
WHERE ancestor_id = $1
ORDER BY path_length ASC
`

func (q *Queries) GetSelfAndDescendantIDs(ctx context.Context, ancestorID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getSelfAndDescendantIDs, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var descendant_id uuid.UUID
		if err := rows.Scan(&descendant_id); err != nil {
			return nil, err
		}
		items = append(items, descendant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFolderPath = `-- name: InsertFolderPath :exec
INSERT INTO folder_paths (ancestor_id, descendant_id, path_length, created_at)
VALUES ($1, $2, $3, NOW())
`

type InsertFolderPathParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	PathLength   int32     `json:"path_length"`
}

func (q *Queries) InsertFolderPath(ctx context.Context, arg InsertFolderPathParams) error {
	_, err := q.db.Exec(ctx, insertFolderPath, arg.AncestorID, arg.DescendantID, arg.PathLength)
	return err
}

type InsertFolderPathsBulkParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	PathLength   int32     `json:"path_length"`
	CreatedAt    time.Time `json:"created_at"`
}
