// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateFolderDepth = `-- name: BulkUpdateFolderDepth :exec
UPDATE folders SET depth = upd.depth, updated_at = NOW()
FROM (SELECT unnest($1::uuid[]) as id, unnest($2::int[]) as depth) as upd
WHERE folders.id = upd.id
`

type BulkUpdateFolderDepthParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []int32     `json:"column_2"`
}

func (q *Queries) BulkUpdateFolderDepth(ctx context.Context, arg BulkUpdateFolderDepthParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateFolderDepth, arg.Column1, arg.Column2)
	return err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
    id, name, parent_id, owner_id, created_by, depth, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status
`

type CreateFolderParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	OwnerID   uuid.UUID   `json:"owner_id"`
	CreatedBy uuid.UUID   `json:"created_by"`
	Depth     int32       `json:"depth"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.OwnerID,
		arg.CreatedBy,
		arg.Depth,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.OwnerID,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Status,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const deleteFoldersBulk = `-- name: DeleteFoldersBulk :exec
DELETE FROM folders WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteFoldersBulk(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFoldersBulk, dollar_1)
	return err
}

const folderExistsByID = `-- name: FolderExistsByID :one
SELECT EXISTS(SELECT 1 FROM folders WHERE id = $1)
`

func (q *Queries) FolderExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, folderExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const folderExistsByNameAndParent = `-- name: FolderExistsByNameAndParent :one
SELECT EXISTS(
    SELECT 1 FROM folders
    WHERE parent_id = $1 AND owner_id = $2 AND name = $3
)
`

type FolderExistsByNameAndParentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	OwnerID  uuid.UUID   `json:"owner_id"`
	Name     string      `json:"name"`
}

func (q *Queries) FolderExistsByNameAndParent(ctx context.Context, arg FolderExistsByNameAndParentParams) (bool, error) {
	row := q.db.QueryRow(ctx, folderExistsByNameAndParent, arg.ParentID, arg.OwnerID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const folderExistsByNameAndParentNullable = `-- name: FolderExistsByNameAndParentNullable :one
SELECT EXISTS(
    SELECT 1 FROM folders
    WHERE (($1::uuid IS NULL AND parent_id IS NULL) OR parent_id = $1) AND owner_id = $2 AND name = $3
)
`

type FolderExistsByNameAndParentNullableParams struct {
	Column1 uuid.UUID `json:"column_1"`
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) FolderExistsByNameAndParentNullable(ctx context.Context, arg FolderExistsByNameAndParentNullableParams) (bool, error) {
	row := q.db.QueryRow(ctx, folderExistsByNameAndParentNullable, arg.Column1, arg.OwnerID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const folderExistsByNameAtRoot = `-- name: FolderExistsByNameAtRoot :one
SELECT EXISTS(
    SELECT 1 FROM folders
    WHERE parent_id IS NULL AND owner_id = $1 AND name = $2
)
`

type FolderExistsByNameAtRootParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) FolderExistsByNameAtRoot(ctx context.Context, arg FolderExistsByNameAtRootParams) (bool, error) {
	row := q.db.QueryRow(ctx, folderExistsByNameAtRoot, arg.OwnerID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status FROM folders WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.OwnerID,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Status,
	)
	return i, err
}

const listFoldersByCreatedBy = `-- name: ListFoldersByCreatedBy :many
SELECT id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status FROM folders
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFoldersByCreatedBy(ctx context.Context, createdBy uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.OwnerID,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByOwner = `-- name: ListFoldersByOwner :many
SELECT id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status FROM folders
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFoldersByOwner(ctx context.Context, ownerID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.OwnerID,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParentID = `-- name: ListFoldersByParentID :many
SELECT id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status FROM folders
WHERE parent_id = $1 AND owner_id = $2
ORDER BY name ASC
`

type ListFoldersByParentIDParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	OwnerID  uuid.UUID   `json:"owner_id"`
}

func (q *Queries) ListFoldersByParentID(ctx context.Context, arg ListFoldersByParentIDParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParentID, arg.ParentID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.OwnerID,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParentIDNullable = `-- name: ListFoldersByParentIDNullable :many
SELECT id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status FROM folders
WHERE (($1::uuid IS NULL AND parent_id IS NULL) OR parent_id = $1) AND owner_id = $2
ORDER BY name ASC
`

type ListFoldersByParentIDNullableParams struct {
	Column1 uuid.UUID `json:"column_1"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) ListFoldersByParentIDNullable(ctx context.Context, arg ListFoldersByParentIDNullableParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParentIDNullable, arg.Column1, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.OwnerID,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFoldersByOwner = `-- name: ListRootFoldersByOwner :many
SELECT id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status FROM folders
WHERE parent_id IS NULL AND owner_id = $1
ORDER BY name ASC
`

func (q *Queries) ListRootFoldersByOwner(ctx context.Context, ownerID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFoldersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.OwnerID,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferFolderOwnership = `-- name: TransferFolderOwnership :exec
UPDATE folders SET owner_id = $2, updated_at = NOW() WHERE id = $1
`

type TransferFolderOwnershipParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) TransferFolderOwnership(ctx context.Context, arg TransferFolderOwnershipParams) error {
	_, err := q.db.Exec(ctx, transferFolderOwnership, arg.ID, arg.OwnerID)
	return err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders SET
    name = COALESCE($2, name),
    parent_id = COALESCE($3, parent_id),
    depth = COALESCE($4, depth),
    owner_id = COALESCE($5, owner_id),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, parent_id, owner_id, depth, created_at, updated_at, created_by, status
`

type UpdateFolderParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     *string     `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
	Depth    *int32      `json:"depth"`
	OwnerID  pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Depth,
		arg.OwnerID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.OwnerID,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Status,
	)
	return i, err
}

const updateFolderDepth = `-- name: UpdateFolderDepth :exec
UPDATE folders SET depth = $2, updated_at = NOW() WHERE id = $1
`

type UpdateFolderDepthParams struct {
	ID    uuid.UUID `json:"id"`
	Depth int32     `json:"depth"`
}

func (q *Queries) UpdateFolderDepth(ctx context.Context, arg UpdateFolderDepthParams) error {
	_, err := q.db.Exec(ctx, updateFolderDepth, arg.ID, arg.Depth)
	return err
}
