// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    id, name, description, owner_id, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, description, owner_id, status, created_at, updated_at
`

type CreateGroupParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, owner_id, status, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupExistsByID = `-- name: GroupExistsByID :one
SELECT EXISTS(SELECT 1 FROM groups WHERE id = $1)
`

func (q *Queries) GroupExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, groupExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveGroupsByOwnerID = `-- name: ListActiveGroupsByOwnerID :many
SELECT id, name, description, owner_id, status, created_at, updated_at FROM groups WHERE owner_id = $1 AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListActiveGroupsByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listActiveGroupsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByMemberID = `-- name: ListGroupsByMemberID :many
SELECT g.id, g.name, g.description, g.owner_id, g.status, g.created_at, g.updated_at FROM groups g
INNER JOIN memberships m ON g.id = m.group_id
WHERE m.user_id = $1 AND g.status = 'active'
ORDER BY g.created_at DESC
`

func (q *Queries) ListGroupsByMemberID(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByMemberID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByOwnerID = `-- name: ListGroupsByOwnerID :many
SELECT id, name, description, owner_id, status, created_at, updated_at FROM groups WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGroupsByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups SET status = 'deleted', updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGroup, id)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    owner_id = COALESCE($4, owner_id),
    status = COALESCE($5, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, owner_id, status, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Status      *string     `json:"status"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Status,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
