// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET status = 'accepted', accepted_at = NOW() WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const countPendingInvitationsByGroupID = `-- name: CountPendingInvitationsByGroupID :one
SELECT COUNT(*) FROM invitations WHERE group_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingInvitationsByGroupID(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitationsByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    id, group_id, email, role, token, invited_by, status, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, group_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	InvitedBy uuid.UUID `json:"invited_by"`
	Status    string    `json:"status"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.GroupID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :exec
DELETE FROM invitations WHERE expires_at < NOW() AND status = 'pending'
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvitations)
	return err
}

const expireInvitation = `-- name: ExpireInvitation :exec
UPDATE invitations SET status = 'expired' WHERE id = $1
`

func (q *Queries) ExpireInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, group_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, group_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at FROM invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitation = `-- name: GetPendingInvitation :one
SELECT id, group_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at FROM invitations
WHERE group_id = $1 AND email = $2 AND status = 'pending'
`

type GetPendingInvitationParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Email   string    `json:"email"`
}

func (q *Queries) GetPendingInvitation(ctx context.Context, arg GetPendingInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitation, arg.GroupID, arg.Email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsByGroupID = `-- name: ListInvitationsByGroupID :many
SELECT id, group_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at FROM invitations
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByGroupID(ctx context.Context, groupID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByEmail = `-- name: ListPendingInvitationsByEmail :many
SELECT id, group_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at FROM invitations
WHERE email = $1 AND status = 'pending' AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByEmail(ctx context.Context, email string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations SET status = 'revoked' WHERE id = $1
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}
