// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    id, group_id, email, token, role, invited_by, expires_at, status, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, group_id, email, token, role, invited_by, expires_at, status, created_at
`

type CreateInvitationParams struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	Email     string    `json:"email"`
	Token     string    `json:"token"`
	Role      string    `json:"role"`
	InvitedBy uuid.UUID `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.GroupID,
		arg.Email,
		arg.Token,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.Status,
		arg.CreatedAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const deleteInvitationsByGroupID = `-- name: DeleteInvitationsByGroupID :exec
DELETE FROM invitations WHERE group_id = $1
`

func (q *Queries) DeleteInvitationsByGroupID(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitationsByGroupID, groupID)
	return err
}

const expireOldInvitations = `-- name: ExpireOldInvitations :execrows
UPDATE invitations
SET status = 'expired'
WHERE status = 'pending' AND expires_at < NOW()
`

func (q *Queries) ExpireOldInvitations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldInvitations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, group_id, email, token, role, invited_by, expires_at, status, created_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, group_id, email, token, role, invited_by, expires_at, status, created_at FROM invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitationByGroupAndEmail = `-- name: GetPendingInvitationByGroupAndEmail :one
SELECT id, group_id, email, token, role, invited_by, expires_at, status, created_at FROM invitations
WHERE group_id = $1 AND email = $2 AND status = 'pending'
`

type GetPendingInvitationByGroupAndEmailParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Email   string    `json:"email"`
}

func (q *Queries) GetPendingInvitationByGroupAndEmail(ctx context.Context, arg GetPendingInvitationByGroupAndEmailParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByGroupAndEmail, arg.GroupID, arg.Email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitationsByEmail = `-- name: ListPendingInvitationsByEmail :many
SELECT id, group_id, email, token, role, invited_by, expires_at, status, created_at FROM invitations
WHERE email = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByEmail(ctx context.Context, email string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByGroupID = `-- name: ListPendingInvitationsByGroupID :many
SELECT id, group_id, email, token, role, invited_by, expires_at, status, created_at FROM invitations
WHERE group_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByGroupID(ctx context.Context, groupID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitation = `-- name: UpdateInvitation :one
UPDATE invitations SET
    status = COALESCE($2, status)
WHERE id = $1
RETURNING id, group_id, email, token, role, invited_by, expires_at, status, created_at
`

type UpdateInvitationParams struct {
	ID     uuid.UUID `json:"id"`
	Status *string   `json:"status"`
}

func (q *Queries) UpdateInvitation(ctx context.Context, arg UpdateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, updateInvitation, arg.ID, arg.Status)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
