// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembershipsByGroupID = `-- name: CountMembershipsByGroupID :one
SELECT COUNT(*) FROM memberships WHERE group_id = $1
`

func (q *Queries) CountMembershipsByGroupID(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    id, group_id, user_id, role, joined_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, group_id, user_id, role, joined_at
`

type CreateMembershipParams struct {
	ID       uuid.UUID `json:"id"`
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE id = $1
`

func (q *Queries) DeleteMembership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembership, id)
	return err
}

const deleteMembershipsByGroupID = `-- name: DeleteMembershipsByGroupID :exec
DELETE FROM memberships WHERE group_id = $1
`

func (q *Queries) DeleteMembershipsByGroupID(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembershipsByGroupID, groupID)
	return err
}

const getMembershipByGroupAndUser = `-- name: GetMembershipByGroupAndUser :one
SELECT id, group_id, user_id, role, joined_at FROM memberships WHERE group_id = $1 AND user_id = $2
`

type GetMembershipByGroupAndUserParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipByGroupAndUser(ctx context.Context, arg GetMembershipByGroupAndUserParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByGroupAndUser, arg.GroupID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, group_id, user_id, role, joined_at FROM memberships WHERE id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listMembershipsByGroupID = `-- name: ListMembershipsByGroupID :many
SELECT id, group_id, user_id, role, joined_at FROM memberships WHERE group_id = $1 ORDER BY joined_at ASC
`

func (q *Queries) ListMembershipsByGroupID(ctx context.Context, groupID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByGroupIDWithUsers = `-- name: ListMembershipsByGroupIDWithUsers :many
SELECT
    m.id, m.group_id, m.user_id, m.role, m.joined_at,
    u.email, u.display_name, u.status as user_status
FROM memberships m
INNER JOIN users u ON m.user_id = u.id
WHERE m.group_id = $1
ORDER BY m.joined_at ASC
`

type ListMembershipsByGroupIDWithUsersRow struct {
	ID          uuid.UUID `json:"id"`
	GroupID     uuid.UUID `json:"group_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	JoinedAt    time.Time `json:"joined_at"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	UserStatus  string    `json:"user_status"`
}

func (q *Queries) ListMembershipsByGroupIDWithUsers(ctx context.Context, groupID uuid.UUID) ([]ListMembershipsByGroupIDWithUsersRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByGroupIDWithUsers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByGroupIDWithUsersRow{}
	for rows.Next() {
		var i ListMembershipsByGroupIDWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.DisplayName,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUserID = `-- name: ListMembershipsByUserID :many
SELECT id, group_id, user_id, role, joined_at FROM memberships WHERE user_id = $1
`

func (q *Queries) ListMembershipsByUserID(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipExists = `-- name: MembershipExists :one
SELECT EXISTS(SELECT 1 FROM memberships WHERE group_id = $1 AND user_id = $2)
`

type MembershipExistsParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE memberships SET
    role = COALESCE($2, role)
WHERE id = $1
RETURNING id, group_id, user_id, role, joined_at
`

type UpdateMembershipParams struct {
	ID   uuid.UUID `json:"id"`
	Role *string   `json:"role"`
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembership, arg.ID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
