// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembershipsByGroupID = `-- name: CountMembershipsByGroupID :one
SELECT COUNT(*) FROM memberships WHERE group_id = $1
`

func (q *Queries) CountMembershipsByGroupID(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    id, group_id, user_id, role, joined_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, group_id, user_id, role, joined_at
`

type CreateMembershipParams struct {
	ID       uuid.UUID `json:"id"`
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE group_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.GroupID, arg.UserID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, group_id, user_id, role, joined_at FROM memberships
WHERE group_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.GroupID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, group_id, user_id, role, joined_at FROM memberships WHERE id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listMembershipsByGroupID = `-- name: ListMembershipsByGroupID :many
SELECT id, group_id, user_id, role, joined_at FROM memberships
WHERE group_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListMembershipsByGroupID(ctx context.Context, groupID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUserID = `-- name: ListMembershipsByUserID :many
SELECT id, group_id, user_id, role, joined_at FROM memberships WHERE user_id = $1
`

func (q *Queries) ListMembershipsByUserID(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipExists = `-- name: MembershipExists :one
SELECT EXISTS(SELECT 1 FROM memberships WHERE group_id = $1 AND user_id = $2)
`

type MembershipExistsParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE memberships SET role = $3
WHERE group_id = $1 AND user_id = $2
`

type UpdateMembershipRoleParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}
