// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type File struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	FolderID       pgtype.UUID        `json:"folder_id"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	MimeType       string             `json:"mime_type"`
	Size           int64              `json:"size"`
	StorageKey     string             `json:"storage_key"`
	CurrentVersion int32              `json:"current_version"`
	Status         string             `json:"status"`
	Checksum       *string            `json:"checksum"`
	TrashedAt      pgtype.Timestamptz `json:"trashed_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type FileVersion struct {
	ID            uuid.UUID `json:"id"`
	FileID        uuid.UUID `json:"file_id"`
	VersionNumber int32     `json:"version_number"`
	Size          int64     `json:"size"`
	StorageKey    string    `json:"storage_key"`
	Checksum      *string   `json:"checksum"`
	CreatedBy     uuid.UUID `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
}

type Folder struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	Path      string             `json:"path"`
	Depth     int32              `json:"depth"`
	IsRoot    bool               `json:"is_root"`
	TrashedAt pgtype.Timestamptz `json:"trashed_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

type Group struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	OwnerID     uuid.UUID `json:"owner_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Invitation struct {
	ID         uuid.UUID          `json:"id"`
	GroupID    uuid.UUID          `json:"group_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	InvitedBy  uuid.UUID          `json:"invited_by"`
	Status     string             `json:"status"`
	ExpiresAt  time.Time          `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Membership struct {
	ID       uuid.UUID `json:"id"`
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type OauthAccount struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type PermissionGrant struct {
	ID           uuid.UUID          `json:"id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   uuid.UUID          `json:"resource_id"`
	GranteeType  string             `json:"grantee_type"`
	GranteeID    uuid.UUID          `json:"grantee_id"`
	Permission   string             `json:"permission"`
	GrantedBy    uuid.UUID          `json:"granted_by"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Relationship struct {
	ID              uuid.UUID `json:"id"`
	ObjectType      string    `json:"object_type"`
	ObjectID        uuid.UUID `json:"object_id"`
	Relation        string    `json:"relation"`
	SubjectType     string    `json:"subject_type"`
	SubjectID       uuid.UUID `json:"subject_id"`
	SubjectRelation *string   `json:"subject_relation"`
	CreatedAt       time.Time `json:"created_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	CreatedAt        time.Time          `json:"created_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type ShareLink struct {
	ID            uuid.UUID          `json:"id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    uuid.UUID          `json:"resource_id"`
	Token         string             `json:"token"`
	Permission    string             `json:"permission"`
	PasswordHash  *string            `json:"password_hash"`
	MaxDownloads  *int32             `json:"max_downloads"`
	DownloadCount int32              `json:"download_count"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	IsActive      bool               `json:"is_active"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type ShareLinkAccess struct {
	ID          uuid.UUID   `json:"id"`
	ShareLinkID uuid.UUID   `json:"share_link_id"`
	AccessedBy  pgtype.UUID `json:"accessed_by"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   *string     `json:"user_agent"`
	Action      string      `json:"action"`
	AccessedAt  time.Time   `json:"accessed_at"`
}

type UploadSession struct {
	ID             uuid.UUID          `json:"id"`
	FileID         uuid.UUID          `json:"file_id"`
	UploadID       *string            `json:"upload_id"`
	Status         string             `json:"status"`
	TotalParts     *int32             `json:"total_parts"`
	CompletedParts *int32             `json:"completed_parts"`
	ExpiresAt      time.Time          `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    *string            `json:"password_hash"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       *string            `json:"avatar_url"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}
