// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_accounts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (
    id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :exec
DELETE FROM oauth_accounts WHERE id = $1
`

func (q *Queries) DeleteOAuthAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccount, id)
	return err
}

const deleteOAuthAccountByUserAndProvider = `-- name: DeleteOAuthAccountByUserAndProvider :exec
DELETE FROM oauth_accounts WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthAccountByUserAndProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteOAuthAccountByUserAndProvider(ctx context.Context, arg DeleteOAuthAccountByUserAndProviderParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccountByUserAndProvider, arg.UserID, arg.Provider)
	return err
}

const getOAuthAccountByProviderAndUserID = `-- name: GetOAuthAccountByProviderAndUserID :one
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountByProviderAndUserIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthAccountByProviderAndUserID(ctx context.Context, arg GetOAuthAccountByProviderAndUserIDParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByProviderAndUserID, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountsByUserID = `-- name: GetOAuthAccountsByUserID :many
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_accounts WHERE user_id = $1
`

func (q *Queries) GetOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, getOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthTokens = `-- name: UpdateOAuthTokens :exec
UPDATE oauth_accounts SET
    access_token = $2,
    refresh_token = $3,
    expires_at = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOAuthTokensParams struct {
	ID           uuid.UUID          `json:"id"`
	AccessToken  *string            `json:"access_token"`
	RefreshToken *string            `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error {
	_, err := q.db.Exec(ctx, updateOAuthTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
