// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_grants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkPermission = `-- name: CheckPermission :one
SELECT EXISTS(
    SELECT 1 FROM permission_grants
    WHERE resource_type = $1
      AND resource_id = $2
      AND grantee_type = $3
      AND grantee_id = $4
      AND permission = $5
      AND (expires_at IS NULL OR expires_at > NOW())
)
`

type CheckPermissionParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	GranteeType  string    `json:"grantee_type"`
	GranteeID    uuid.UUID `json:"grantee_id"`
	Permission   string    `json:"permission"`
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermission,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Permission,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPermissionGrant = `-- name: CreatePermissionGrant :one
INSERT INTO permission_grants (
    id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at
`

type CreatePermissionGrantParams struct {
	ID           uuid.UUID          `json:"id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   uuid.UUID          `json:"resource_id"`
	GranteeType  string             `json:"grantee_type"`
	GranteeID    uuid.UUID          `json:"grantee_id"`
	Permission   string             `json:"permission"`
	GrantedBy    uuid.UUID          `json:"granted_by"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePermissionGrant(ctx context.Context, arg CreatePermissionGrantParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, createPermissionGrant,
		arg.ID,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Permission,
		arg.GrantedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredPermissionGrants = `-- name: DeleteExpiredPermissionGrants :exec
DELETE FROM permission_grants WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredPermissionGrants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPermissionGrants)
	return err
}

const deletePermissionGrant = `-- name: DeletePermissionGrant :exec
DELETE FROM permission_grants WHERE id = $1
`

func (q *Queries) DeletePermissionGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermissionGrant, id)
	return err
}

const deletePermissionGrantsByGrantee = `-- name: DeletePermissionGrantsByGrantee :exec
DELETE FROM permission_grants
WHERE grantee_type = $1 AND grantee_id = $2
`

type DeletePermissionGrantsByGranteeParams struct {
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

func (q *Queries) DeletePermissionGrantsByGrantee(ctx context.Context, arg DeletePermissionGrantsByGranteeParams) error {
	_, err := q.db.Exec(ctx, deletePermissionGrantsByGrantee, arg.GranteeType, arg.GranteeID)
	return err
}

const deletePermissionGrantsByResource = `-- name: DeletePermissionGrantsByResource :exec
DELETE FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2
`

type DeletePermissionGrantsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) DeletePermissionGrantsByResource(ctx context.Context, arg DeletePermissionGrantsByResourceParams) error {
	_, err := q.db.Exec(ctx, deletePermissionGrantsByResource, arg.ResourceType, arg.ResourceID)
	return err
}

const getPermissionGrant = `-- name: GetPermissionGrant :one
SELECT id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2 AND grantee_type = $3 AND grantee_id = $4 AND permission = $5
`

type GetPermissionGrantParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	GranteeType  string    `json:"grantee_type"`
	GranteeID    uuid.UUID `json:"grantee_id"`
	Permission   string    `json:"permission"`
}

func (q *Queries) GetPermissionGrant(ctx context.Context, arg GetPermissionGrantParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, getPermissionGrant,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Permission,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPermissionGrantByID = `-- name: GetPermissionGrantByID :one
SELECT id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at FROM permission_grants WHERE id = $1
`

func (q *Queries) GetPermissionGrantByID(ctx context.Context, id uuid.UUID) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, getPermissionGrantByID, id)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listPermissionGrantsByGrantee = `-- name: ListPermissionGrantsByGrantee :many
SELECT id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at FROM permission_grants
WHERE grantee_type = $1 AND grantee_id = $2
ORDER BY created_at ASC
`

type ListPermissionGrantsByGranteeParams struct {
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

func (q *Queries) ListPermissionGrantsByGrantee(ctx context.Context, arg ListPermissionGrantsByGranteeParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listPermissionGrantsByGrantee, arg.GranteeType, arg.GranteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Permission,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionGrantsByResource = `-- name: ListPermissionGrantsByResource :many
SELECT id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at ASC
`

type ListPermissionGrantsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) ListPermissionGrantsByResource(ctx context.Context, arg ListPermissionGrantsByResourceParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listPermissionGrantsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Permission,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT id, resource_type, resource_id, grantee_type, grantee_id, permission, granted_by, created_at, expires_at FROM permission_grants
WHERE grantee_type = 'user' AND grantee_id = $1
AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) ListUserPermissions(ctx context.Context, granteeID uuid.UUID) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, granteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Permission,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
