// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_grants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPermissionGrant = `-- name: CreatePermissionGrant :one
INSERT INTO permission_grants (
    id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at
`

type CreatePermissionGrantParams struct {
	ID           uuid.UUID `json:"id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	GranteeType  string    `json:"grantee_type"`
	GranteeID    uuid.UUID `json:"grantee_id"`
	Role         string    `json:"role"`
	GrantedBy    uuid.UUID `json:"granted_by"`
	GrantedAt    time.Time `json:"granted_at"`
}

func (q *Queries) CreatePermissionGrant(ctx context.Context, arg CreatePermissionGrantParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, createPermissionGrant,
		arg.ID,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Role,
		arg.GrantedBy,
		arg.GrantedAt,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const deletePermissionGrant = `-- name: DeletePermissionGrant :exec
DELETE FROM permission_grants WHERE id = $1
`

func (q *Queries) DeletePermissionGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermissionGrant, id)
	return err
}

const deletePermissionGrantsByGrantee = `-- name: DeletePermissionGrantsByGrantee :exec
DELETE FROM permission_grants WHERE grantee_type = $1 AND grantee_id = $2
`

type DeletePermissionGrantsByGranteeParams struct {
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

func (q *Queries) DeletePermissionGrantsByGrantee(ctx context.Context, arg DeletePermissionGrantsByGranteeParams) error {
	_, err := q.db.Exec(ctx, deletePermissionGrantsByGrantee, arg.GranteeType, arg.GranteeID)
	return err
}

const deletePermissionGrantsByResource = `-- name: DeletePermissionGrantsByResource :exec
DELETE FROM permission_grants WHERE resource_type = $1 AND resource_id = $2
`

type DeletePermissionGrantsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) DeletePermissionGrantsByResource(ctx context.Context, arg DeletePermissionGrantsByResourceParams) error {
	_, err := q.db.Exec(ctx, deletePermissionGrantsByResource, arg.ResourceType, arg.ResourceID)
	return err
}

const deletePermissionGrantsByResourceAndGrantee = `-- name: DeletePermissionGrantsByResourceAndGrantee :exec
DELETE FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2 AND grantee_type = $3 AND grantee_id = $4
`

type DeletePermissionGrantsByResourceAndGranteeParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	GranteeType  string    `json:"grantee_type"`
	GranteeID    uuid.UUID `json:"grantee_id"`
}

func (q *Queries) DeletePermissionGrantsByResourceAndGrantee(ctx context.Context, arg DeletePermissionGrantsByResourceAndGranteeParams) error {
	_, err := q.db.Exec(ctx, deletePermissionGrantsByResourceAndGrantee,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
	)
	return err
}

const getPermissionGrantByID = `-- name: GetPermissionGrantByID :one
SELECT id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at FROM permission_grants WHERE id = $1
`

func (q *Queries) GetPermissionGrantByID(ctx context.Context, id uuid.UUID) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, getPermissionGrantByID, id)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const getPermissionGrantByResourceGranteeAndRole = `-- name: GetPermissionGrantByResourceGranteeAndRole :one
SELECT id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2 AND grantee_type = $3 AND grantee_id = $4 AND role = $5
`

type GetPermissionGrantByResourceGranteeAndRoleParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	GranteeType  string    `json:"grantee_type"`
	GranteeID    uuid.UUID `json:"grantee_id"`
	Role         string    `json:"role"`
}

func (q *Queries) GetPermissionGrantByResourceGranteeAndRole(ctx context.Context, arg GetPermissionGrantByResourceGranteeAndRoleParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, getPermissionGrantByResourceGranteeAndRole,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Role,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const listPermissionGrantsByGrantee = `-- name: ListPermissionGrantsByGrantee :many
SELECT id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at FROM permission_grants
WHERE grantee_type = $1 AND grantee_id = $2
ORDER BY granted_at DESC
`

type ListPermissionGrantsByGranteeParams struct {
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

func (q *Queries) ListPermissionGrantsByGrantee(ctx context.Context, arg ListPermissionGrantsByGranteeParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listPermissionGrantsByGrantee, arg.GranteeType, arg.GranteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Role,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionGrantsByResource = `-- name: ListPermissionGrantsByResource :many
SELECT id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2
ORDER BY granted_at DESC
`

type ListPermissionGrantsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) ListPermissionGrantsByResource(ctx context.Context, arg ListPermissionGrantsByResourceParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listPermissionGrantsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Role,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionGrantsByResourceAndGrantee = `-- name: ListPermissionGrantsByResourceAndGrantee :many
SELECT id, resource_type, resource_id, grantee_type, grantee_id, role, granted_by, granted_at FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2 AND grantee_type = $3 AND grantee_id = $4
ORDER BY granted_at DESC
`

type ListPermissionGrantsByResourceAndGranteeParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	GranteeType  string    `json:"grantee_type"`
	GranteeID    uuid.UUID `json:"grantee_id"`
}

func (q *Queries) ListPermissionGrantsByResourceAndGrantee(ctx context.Context, arg ListPermissionGrantsByResourceAndGranteeParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listPermissionGrantsByResourceAndGrantee,
		arg.ResourceType,
		arg.ResourceID,
		arg.GranteeType,
		arg.GranteeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Role,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
