// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkRelationship = `-- name: CheckRelationship :one
SELECT EXISTS(
    SELECT 1 FROM relationships
    WHERE object_type = $1
      AND object_id = $2
      AND relation = $3
      AND subject_type = $4
      AND subject_id = $5
)
`

type CheckRelationshipParams struct {
	ObjectType  string    `json:"object_type"`
	ObjectID    uuid.UUID `json:"object_id"`
	Relation    string    `json:"relation"`
	SubjectType string    `json:"subject_type"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

func (q *Queries) CheckRelationship(ctx context.Context, arg CheckRelationshipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRelationship,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (
    id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at
`

type CreateRelationshipParams struct {
	ID              uuid.UUID `json:"id"`
	ObjectType      string    `json:"object_type"`
	ObjectID        uuid.UUID `json:"object_id"`
	Relation        string    `json:"relation"`
	SubjectType     string    `json:"subject_type"`
	SubjectID       uuid.UUID `json:"subject_id"`
	SubjectRelation *string   `json:"subject_relation"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.ID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
		arg.CreatedAt,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Relation,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectRelation,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships WHERE id = $1
`

func (q *Queries) DeleteRelationship(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelationship, id)
	return err
}

const deleteRelationshipByTuple = `-- name: DeleteRelationshipByTuple :exec
DELETE FROM relationships
WHERE object_type = $1 AND object_id = $2 AND relation = $3 AND subject_type = $4 AND subject_id = $5
`

type DeleteRelationshipByTupleParams struct {
	ObjectType  string    `json:"object_type"`
	ObjectID    uuid.UUID `json:"object_id"`
	Relation    string    `json:"relation"`
	SubjectType string    `json:"subject_type"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

func (q *Queries) DeleteRelationshipByTuple(ctx context.Context, arg DeleteRelationshipByTupleParams) error {
	_, err := q.db.Exec(ctx, deleteRelationshipByTuple,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
	)
	return err
}

const deleteRelationshipsByObject = `-- name: DeleteRelationshipsByObject :exec
DELETE FROM relationships WHERE object_type = $1 AND object_id = $2
`

type DeleteRelationshipsByObjectParams struct {
	ObjectType string    `json:"object_type"`
	ObjectID   uuid.UUID `json:"object_id"`
}

func (q *Queries) DeleteRelationshipsByObject(ctx context.Context, arg DeleteRelationshipsByObjectParams) error {
	_, err := q.db.Exec(ctx, deleteRelationshipsByObject, arg.ObjectType, arg.ObjectID)
	return err
}

const deleteRelationshipsBySubject = `-- name: DeleteRelationshipsBySubject :exec
DELETE FROM relationships WHERE subject_type = $1 AND subject_id = $2
`

type DeleteRelationshipsBySubjectParams struct {
	SubjectType string    `json:"subject_type"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

func (q *Queries) DeleteRelationshipsBySubject(ctx context.Context, arg DeleteRelationshipsBySubjectParams) error {
	_, err := q.db.Exec(ctx, deleteRelationshipsBySubject, arg.SubjectType, arg.SubjectID)
	return err
}

const getParentRelation = `-- name: GetParentRelation :one
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships
WHERE object_type = 'folder' AND object_id = $1 AND relation = 'parent'
LIMIT 1
`

func (q *Queries) GetParentRelation(ctx context.Context, objectID uuid.UUID) (Relationship, error) {
	row := q.db.QueryRow(ctx, getParentRelation, objectID)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Relation,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectRelation,
		&i.CreatedAt,
	)
	return i, err
}

const getRelationship = `-- name: GetRelationship :one
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships
WHERE object_type = $1 AND object_id = $2 AND relation = $3 AND subject_type = $4 AND subject_id = $5
`

type GetRelationshipParams struct {
	ObjectType  string    `json:"object_type"`
	ObjectID    uuid.UUID `json:"object_id"`
	Relation    string    `json:"relation"`
	SubjectType string    `json:"subject_type"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

func (q *Queries) GetRelationship(ctx context.Context, arg GetRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, getRelationship,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Relation,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectRelation,
		&i.CreatedAt,
	)
	return i, err
}

const getRelationshipByID = `-- name: GetRelationshipByID :one
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships WHERE id = $1
`

func (q *Queries) GetRelationshipByID(ctx context.Context, id uuid.UUID) (Relationship, error) {
	row := q.db.QueryRow(ctx, getRelationshipByID, id)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Relation,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectRelation,
		&i.CreatedAt,
	)
	return i, err
}

const listChildRelations = `-- name: ListChildRelations :many
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships
WHERE relation = 'parent' AND subject_type = 'folder' AND subject_id = $1
`

func (q *Queries) ListChildRelations(ctx context.Context, subjectID uuid.UUID) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, listChildRelations, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByObject = `-- name: ListRelationshipsByObject :many
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships
WHERE object_type = $1 AND object_id = $2
ORDER BY created_at ASC
`

type ListRelationshipsByObjectParams struct {
	ObjectType string    `json:"object_type"`
	ObjectID   uuid.UUID `json:"object_id"`
}

func (q *Queries) ListRelationshipsByObject(ctx context.Context, arg ListRelationshipsByObjectParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByObject, arg.ObjectType, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByObjectAndRelation = `-- name: ListRelationshipsByObjectAndRelation :many
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships
WHERE object_type = $1 AND object_id = $2 AND relation = $3
ORDER BY created_at ASC
`

type ListRelationshipsByObjectAndRelationParams struct {
	ObjectType string    `json:"object_type"`
	ObjectID   uuid.UUID `json:"object_id"`
	Relation   string    `json:"relation"`
}

func (q *Queries) ListRelationshipsByObjectAndRelation(ctx context.Context, arg ListRelationshipsByObjectAndRelationParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByObjectAndRelation, arg.ObjectType, arg.ObjectID, arg.Relation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsBySubject = `-- name: ListRelationshipsBySubject :many
SELECT id, object_type, object_id, relation, subject_type, subject_id, subject_relation, created_at FROM relationships
WHERE subject_type = $1 AND subject_id = $2
ORDER BY created_at ASC
`

type ListRelationshipsBySubjectParams struct {
	SubjectType string    `json:"subject_type"`
	SubjectID   uuid.UUID `json:"subject_id"`
}

func (q *Queries) ListRelationshipsBySubject(ctx context.Context, arg ListRelationshipsBySubjectParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsBySubject, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
