// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_link_accesses.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countShareLinkAccessesByLinkID = `-- name: CountShareLinkAccessesByLinkID :one
SELECT COUNT(*) FROM share_link_accesses WHERE share_link_id = $1
`

func (q *Queries) CountShareLinkAccessesByLinkID(ctx context.Context, shareLinkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShareLinkAccessesByLinkID, shareLinkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShareLinkAccess = `-- name: CreateShareLinkAccess :one
INSERT INTO share_link_accesses (
    id, share_link_id, accessed_at, ip_address, user_agent, user_id, action
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, share_link_id, accessed_at, ip_address, user_agent, user_id, action
`

type CreateShareLinkAccessParams struct {
	ID          uuid.UUID   `json:"id"`
	ShareLinkID uuid.UUID   `json:"share_link_id"`
	AccessedAt  time.Time   `json:"accessed_at"`
	IpAddress   *string     `json:"ip_address"`
	UserAgent   *string     `json:"user_agent"`
	UserID      pgtype.UUID `json:"user_id"`
	Action      string      `json:"action"`
}

func (q *Queries) CreateShareLinkAccess(ctx context.Context, arg CreateShareLinkAccessParams) (ShareLinkAccess, error) {
	row := q.db.QueryRow(ctx, createShareLinkAccess,
		arg.ID,
		arg.ShareLinkID,
		arg.AccessedAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
		arg.Action,
	)
	var i ShareLinkAccess
	err := row.Scan(
		&i.ID,
		&i.ShareLinkID,
		&i.AccessedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.Action,
	)
	return i, err
}

const deleteShareLinkAccessesByLinkID = `-- name: DeleteShareLinkAccessesByLinkID :exec
DELETE FROM share_link_accesses WHERE share_link_id = $1
`

func (q *Queries) DeleteShareLinkAccessesByLinkID(ctx context.Context, shareLinkID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShareLinkAccessesByLinkID, shareLinkID)
	return err
}

const getShareLinkAccessByID = `-- name: GetShareLinkAccessByID :one
SELECT id, share_link_id, accessed_at, ip_address, user_agent, user_id, action FROM share_link_accesses WHERE id = $1
`

func (q *Queries) GetShareLinkAccessByID(ctx context.Context, id uuid.UUID) (ShareLinkAccess, error) {
	row := q.db.QueryRow(ctx, getShareLinkAccessByID, id)
	var i ShareLinkAccess
	err := row.Scan(
		&i.ID,
		&i.ShareLinkID,
		&i.AccessedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.Action,
	)
	return i, err
}

const listShareLinkAccessesByLinkID = `-- name: ListShareLinkAccessesByLinkID :many
SELECT id, share_link_id, accessed_at, ip_address, user_agent, user_id, action FROM share_link_accesses
WHERE share_link_id = $1
ORDER BY accessed_at DESC
`

func (q *Queries) ListShareLinkAccessesByLinkID(ctx context.Context, shareLinkID uuid.UUID) ([]ShareLinkAccess, error) {
	rows, err := q.db.Query(ctx, listShareLinkAccessesByLinkID, shareLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLinkAccess{}
	for rows.Next() {
		var i ShareLinkAccess
		if err := rows.Scan(
			&i.ID,
			&i.ShareLinkID,
			&i.AccessedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.UserID,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareLinkAccessesByLinkIDWithPagination = `-- name: ListShareLinkAccessesByLinkIDWithPagination :many
SELECT id, share_link_id, accessed_at, ip_address, user_agent, user_id, action FROM share_link_accesses
WHERE share_link_id = $1
ORDER BY accessed_at DESC
LIMIT $2 OFFSET $3
`

type ListShareLinkAccessesByLinkIDWithPaginationParams struct {
	ShareLinkID uuid.UUID `json:"share_link_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListShareLinkAccessesByLinkIDWithPagination(ctx context.Context, arg ListShareLinkAccessesByLinkIDWithPaginationParams) ([]ShareLinkAccess, error) {
	rows, err := q.db.Query(ctx, listShareLinkAccessesByLinkIDWithPagination, arg.ShareLinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLinkAccess{}
	for rows.Next() {
		var i ShareLinkAccess
		if err := rows.Scan(
			&i.ID,
			&i.ShareLinkID,
			&i.AccessedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.UserID,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
