// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_link_accesses.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeOldShareLinkAccesses = `-- name: AnonymizeOldShareLinkAccesses :exec
UPDATE share_link_accesses SET
    ip_address = NULL,
    user_agent = NULL
WHERE accessed_at < $1 AND ip_address IS NOT NULL
`

func (q *Queries) AnonymizeOldShareLinkAccesses(ctx context.Context, accessedAt time.Time) error {
	_, err := q.db.Exec(ctx, anonymizeOldShareLinkAccesses, accessedAt)
	return err
}

const countShareLinkAccesses = `-- name: CountShareLinkAccesses :one
SELECT COUNT(*) FROM share_link_accesses WHERE share_link_id = $1
`

func (q *Queries) CountShareLinkAccesses(ctx context.Context, shareLinkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShareLinkAccesses, shareLinkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShareLinkDownloads = `-- name: CountShareLinkDownloads :one
SELECT COUNT(*) FROM share_link_accesses
WHERE share_link_id = $1 AND action = 'download'
`

func (q *Queries) CountShareLinkDownloads(ctx context.Context, shareLinkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShareLinkDownloads, shareLinkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShareLinkAccess = `-- name: CreateShareLinkAccess :one
INSERT INTO share_link_accesses (
    id, share_link_id, accessed_by, ip_address, user_agent, action, accessed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, share_link_id, accessed_by, ip_address, user_agent, action, accessed_at
`

type CreateShareLinkAccessParams struct {
	ID          uuid.UUID   `json:"id"`
	ShareLinkID uuid.UUID   `json:"share_link_id"`
	AccessedBy  pgtype.UUID `json:"accessed_by"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   *string     `json:"user_agent"`
	Action      string      `json:"action"`
	AccessedAt  time.Time   `json:"accessed_at"`
}

func (q *Queries) CreateShareLinkAccess(ctx context.Context, arg CreateShareLinkAccessParams) (ShareLinkAccess, error) {
	row := q.db.QueryRow(ctx, createShareLinkAccess,
		arg.ID,
		arg.ShareLinkID,
		arg.AccessedBy,
		arg.IpAddress,
		arg.UserAgent,
		arg.Action,
		arg.AccessedAt,
	)
	var i ShareLinkAccess
	err := row.Scan(
		&i.ID,
		&i.ShareLinkID,
		&i.AccessedBy,
		&i.IpAddress,
		&i.UserAgent,
		&i.Action,
		&i.AccessedAt,
	)
	return i, err
}

const deleteOldShareLinkAccesses = `-- name: DeleteOldShareLinkAccesses :exec
DELETE FROM share_link_accesses WHERE accessed_at < $1
`

func (q *Queries) DeleteOldShareLinkAccesses(ctx context.Context, accessedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldShareLinkAccesses, accessedAt)
	return err
}

const getRecentShareLinkAccesses = `-- name: GetRecentShareLinkAccesses :many
SELECT id, share_link_id, accessed_by, ip_address, user_agent, action, accessed_at FROM share_link_accesses
WHERE share_link_id = $1 AND accessed_at > $2
ORDER BY accessed_at DESC
`

type GetRecentShareLinkAccessesParams struct {
	ShareLinkID uuid.UUID `json:"share_link_id"`
	AccessedAt  time.Time `json:"accessed_at"`
}

func (q *Queries) GetRecentShareLinkAccesses(ctx context.Context, arg GetRecentShareLinkAccessesParams) ([]ShareLinkAccess, error) {
	rows, err := q.db.Query(ctx, getRecentShareLinkAccesses, arg.ShareLinkID, arg.AccessedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLinkAccess{}
	for rows.Next() {
		var i ShareLinkAccess
		if err := rows.Scan(
			&i.ID,
			&i.ShareLinkID,
			&i.AccessedBy,
			&i.IpAddress,
			&i.UserAgent,
			&i.Action,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareLinkAccessesByLinkID = `-- name: ListShareLinkAccessesByLinkID :many
SELECT id, share_link_id, accessed_by, ip_address, user_agent, action, accessed_at FROM share_link_accesses
WHERE share_link_id = $1
ORDER BY accessed_at DESC
LIMIT $2 OFFSET $3
`

type ListShareLinkAccessesByLinkIDParams struct {
	ShareLinkID uuid.UUID `json:"share_link_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListShareLinkAccessesByLinkID(ctx context.Context, arg ListShareLinkAccessesByLinkIDParams) ([]ShareLinkAccess, error) {
	rows, err := q.db.Query(ctx, listShareLinkAccessesByLinkID, arg.ShareLinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLinkAccess{}
	for rows.Next() {
		var i ShareLinkAccess
		if err := rows.Scan(
			&i.ID,
			&i.ShareLinkID,
			&i.AccessedBy,
			&i.IpAddress,
			&i.UserAgent,
			&i.Action,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
