// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_parts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUploadPart = `-- name: CreateUploadPart :one
INSERT INTO upload_parts (
    id, session_id, part_number, size, etag, uploaded_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, session_id, part_number, size, etag, uploaded_at
`

type CreateUploadPartParams struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	PartNumber int32     `json:"part_number"`
	Size       int64     `json:"size"`
	Etag       string    `json:"etag"`
	UploadedAt time.Time `json:"uploaded_at"`
}

func (q *Queries) CreateUploadPart(ctx context.Context, arg CreateUploadPartParams) (UploadPart, error) {
	row := q.db.QueryRow(ctx, createUploadPart,
		arg.ID,
		arg.SessionID,
		arg.PartNumber,
		arg.Size,
		arg.Etag,
		arg.UploadedAt,
	)
	var i UploadPart
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PartNumber,
		&i.Size,
		&i.Etag,
		&i.UploadedAt,
	)
	return i, err
}

const deleteUploadPartsBySessionID = `-- name: DeleteUploadPartsBySessionID :exec
DELETE FROM upload_parts WHERE session_id = $1
`

func (q *Queries) DeleteUploadPartsBySessionID(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUploadPartsBySessionID, sessionID)
	return err
}

const listUploadPartsBySessionID = `-- name: ListUploadPartsBySessionID :many
SELECT id, session_id, part_number, size, etag, uploaded_at FROM upload_parts
WHERE session_id = $1
ORDER BY part_number ASC
`

func (q *Queries) ListUploadPartsBySessionID(ctx context.Context, sessionID uuid.UUID) ([]UploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadPartsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadPart{}
	for rows.Next() {
		var i UploadPart
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PartNumber,
			&i.Size,
			&i.Etag,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
