// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
    id, user_id, avatar_url, bio, timezone, locale, theme, notification_preferences, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, avatar_url, bio, timezone, locale, theme, notification_preferences, created_at, updated_at
`

type CreateUserProfileParams struct {
	ID                      uuid.UUID `json:"id"`
	UserID                  uuid.UUID `json:"user_id"`
	AvatarUrl               *string   `json:"avatar_url"`
	Bio                     *string   `json:"bio"`
	Timezone                *string   `json:"timezone"`
	Locale                  *string   `json:"locale"`
	Theme                   *string   `json:"theme"`
	NotificationPreferences []byte    `json:"notification_preferences"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.ID,
		arg.UserID,
		arg.AvatarUrl,
		arg.Bio,
		arg.Timezone,
		arg.Locale,
		arg.Theme,
		arg.NotificationPreferences,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.Locale,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserProfile = `-- name: DeleteUserProfile :exec
DELETE FROM user_profiles WHERE user_id = $1
`

func (q *Queries) DeleteUserProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserProfile, userID)
	return err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT id, user_id, avatar_url, bio, timezone, locale, theme, notification_preferences, created_at, updated_at FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.Locale,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles SET
    avatar_url = COALESCE($2, avatar_url),
    bio = COALESCE($3, bio),
    locale = COALESCE($4, locale),
    timezone = COALESCE($5, timezone),
    theme = COALESCE($6, theme),
    notification_preferences = COALESCE($7, notification_preferences),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, avatar_url, bio, timezone, locale, theme, notification_preferences, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserID                  uuid.UUID `json:"user_id"`
	AvatarUrl               *string   `json:"avatar_url"`
	Bio                     *string   `json:"bio"`
	Locale                  *string   `json:"locale"`
	Timezone                *string   `json:"timezone"`
	Theme                   *string   `json:"theme"`
	NotificationPreferences []byte    `json:"notification_preferences"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.AvatarUrl,
		arg.Bio,
		arg.Locale,
		arg.Timezone,
		arg.Theme,
		arg.NotificationPreferences,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.Locale,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (
    id, user_id, avatar_url, bio, locale, timezone, theme, notification_preferences, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
    avatar_url = COALESCE(EXCLUDED.avatar_url, user_profiles.avatar_url),
    bio = COALESCE(EXCLUDED.bio, user_profiles.bio),
    locale = COALESCE(EXCLUDED.locale, user_profiles.locale),
    timezone = COALESCE(EXCLUDED.timezone, user_profiles.timezone),
    theme = COALESCE(EXCLUDED.theme, user_profiles.theme),
    notification_preferences = COALESCE(EXCLUDED.notification_preferences, user_profiles.notification_preferences),
    updated_at = NOW()
RETURNING id, user_id, avatar_url, bio, timezone, locale, theme, notification_preferences, created_at, updated_at
`

type UpsertUserProfileParams struct {
	ID                      uuid.UUID `json:"id"`
	UserID                  uuid.UUID `json:"user_id"`
	AvatarUrl               *string   `json:"avatar_url"`
	Bio                     *string   `json:"bio"`
	Locale                  *string   `json:"locale"`
	Timezone                *string   `json:"timezone"`
	Theme                   *string   `json:"theme"`
	NotificationPreferences []byte    `json:"notification_preferences"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ID,
		arg.UserID,
		arg.AvatarUrl,
		arg.Bio,
		arg.Locale,
		arg.Timezone,
		arg.Theme,
		arg.NotificationPreferences,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.Locale,
		&i.Theme,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
