// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
    user_id, display_name, avatar_url, bio, locale, timezone, settings, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING user_id, display_name, avatar_url, bio, locale, timezone, settings, updated_at
`

type CreateUserProfileParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	DisplayName *string         `json:"display_name"`
	AvatarUrl   *string         `json:"avatar_url"`
	Bio         *string         `json:"bio"`
	Locale      string          `json:"locale"`
	Timezone    string          `json:"timezone"`
	Settings    json.RawMessage `json:"settings"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.Locale,
		arg.Timezone,
		arg.Settings,
		arg.UpdatedAt,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Locale,
		&i.Timezone,
		&i.Settings,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserProfile = `-- name: DeleteUserProfile :exec
DELETE FROM user_profiles WHERE user_id = $1
`

func (q *Queries) DeleteUserProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserProfile, userID)
	return err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT user_id, display_name, avatar_url, bio, locale, timezone, settings, updated_at FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Locale,
		&i.Timezone,
		&i.Settings,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles SET
    display_name = COALESCE($2, display_name),
    avatar_url = COALESCE($3, avatar_url),
    bio = COALESCE($4, bio),
    locale = COALESCE($5, locale),
    timezone = COALESCE($6, timezone),
    settings = COALESCE($7, settings),
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, display_name, avatar_url, bio, locale, timezone, settings, updated_at
`

type UpdateUserProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName *string   `json:"display_name"`
	AvatarUrl   *string   `json:"avatar_url"`
	Bio         *string   `json:"bio"`
	Locale      *string   `json:"locale"`
	Timezone    *string   `json:"timezone"`
	Settings    []byte    `json:"settings"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.Locale,
		arg.Timezone,
		arg.Settings,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Locale,
		&i.Timezone,
		&i.Settings,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (
    user_id, display_name, avatar_url, bio, locale, timezone, settings, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = COALESCE(EXCLUDED.display_name, user_profiles.display_name),
    avatar_url = COALESCE(EXCLUDED.avatar_url, user_profiles.avatar_url),
    bio = COALESCE(EXCLUDED.bio, user_profiles.bio),
    locale = COALESCE(EXCLUDED.locale, user_profiles.locale),
    timezone = COALESCE(EXCLUDED.timezone, user_profiles.timezone),
    settings = COALESCE(EXCLUDED.settings, user_profiles.settings),
    updated_at = NOW()
RETURNING user_id, display_name, avatar_url, bio, locale, timezone, settings, updated_at
`

type UpsertUserProfileParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	DisplayName *string         `json:"display_name"`
	AvatarUrl   *string         `json:"avatar_url"`
	Bio         *string         `json:"bio"`
	Locale      string          `json:"locale"`
	Timezone    string          `json:"timezone"`
	Settings    json.RawMessage `json:"settings"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.Locale,
		arg.Timezone,
		arg.Settings,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Locale,
		&i.Timezone,
		&i.Settings,
		&i.UpdatedAt,
	)
	return i, err
}
