version: '3'

dotenv: ['.env.local', '.env']

vars:
  BACKEND_DIR: ./backend
  FRONTEND_DIR: ./frontend
  MIGRATIONS_DIR: ./migrations

tasks:
  # =============================================================================
  # Quick Start
  # =============================================================================
  dev:
    desc: Start full development environment (infra + backend + frontend)
    deps: [infra:up]
    cmds:
      - task: migrate:up
      - defer: { task: infra:down }
      - task: dev:services

  dev:services:
    desc: Start backend and frontend in parallel
    deps: [backend:dev, frontend:dev]

  # =============================================================================
  # Infrastructure
  # =============================================================================
  infra:up:
    desc: Start infrastructure services (PostgreSQL, Redis, MinIO, MailHog)
    cmds:
      - docker compose up -d
      - echo "Waiting for services to be ready..."
      - sleep 3
      - docker compose ps

  infra:down:
    desc: Stop infrastructure services and remove volumes
    cmds:
      - docker compose down -v

  infra:logs:
    desc: View infrastructure logs
    cmds:
      - docker compose logs -f

  infra:status:
    desc: Check infrastructure status
    cmds:
      - docker compose ps

  # =============================================================================
  # Backend
  # =============================================================================
  backend:dev:
    desc: Start backend with hot reload (Air)
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - air

  backend:build:
    desc: Build backend binary
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o bin/api cmd/api/main.go

  backend:test:
    desc: Run backend tests
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test -v ./...

  backend:test-coverage:
    desc: Run backend tests with coverage
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  backend:lint:
    desc: Run golangci-lint
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - golangci-lint run ./...

  backend:fmt:
    desc: Format Go code
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go fmt ./...

  backend:sqlc:
    desc: Generate Go code from SQL
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - sqlc generate

  backend:generate-mocks:
    desc: Generate mocks using gomock
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go generate ./...

  # =============================================================================
  # Frontend
  # =============================================================================
  frontend:dev:
    desc: Start frontend development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm dev

  frontend:build:
    desc: Build frontend for production
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build

  frontend:test:
    desc: Run frontend tests
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm test

  frontend:test-watch:
    desc: Run frontend tests in watch mode
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm test:watch

  frontend:lint:
    desc: Run ESLint
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm lint

  frontend:format:
    desc: Format code with Prettier
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm format

  # =============================================================================
  # Database Migrations
  # =============================================================================
  migrate:up:
    desc: Apply all pending migrations
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" up

  migrate:down:
    desc: Rollback the last migration
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" down 1

  migrate:create:
    desc: "Create a new migration (usage: task migrate:create NAME=create_users)"
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.NAME}}

  migrate:version:
    desc: Show current migration version
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" version

  migrate:force:
    desc: "Force set migration version (usage: task migrate:force VERSION=1)"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" force {{.VERSION}}

  # =============================================================================
  # Setup
  # =============================================================================
  setup:
    desc: Initial project setup
    cmds:
      - task: setup:tools
      - task: setup:backend
      - task: setup:frontend

  setup:tools:
    desc: Install required development tools
    cmds:
      - echo "Installing Go tools..."
      - go install github.com/air-verse/air@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - echo "Tools installed successfully!"

  setup:backend:
    desc: Setup backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod download

  setup:frontend:
    desc: Setup frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm install

  # =============================================================================
  # Utilities
  # =============================================================================
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BACKEND_DIR}}/bin
      - rm -rf {{.BACKEND_DIR}}/coverage.out
      - rm -rf {{.BACKEND_DIR}}/coverage.html
      - rm -rf {{.FRONTEND_DIR}}/dist
      - rm -rf {{.FRONTEND_DIR}}/coverage

  db:connect:
    desc: Connect to PostgreSQL database
    cmds:
      - docker compose exec postgres psql -U postgres -d gc_storage

  db:reset:
    desc: Reset database (drop and recreate)
    cmds:
      - docker compose exec postgres psql -U postgres -c "DROP DATABASE IF EXISTS gc_storage;"
      - docker compose exec postgres psql -U postgres -c "CREATE DATABASE gc_storage;"
      - task: migrate:up
