version: '3'

dotenv: ['.env.local', '.env']

vars:
  BACKEND_DIR: ./backend
  FRONTEND_DIR: ./frontend
  MIGRATIONS_DIR: ./backend/internal/infrastructure/database/migrations

tasks:
  # =============================================================================
  # Quick Start
  # =============================================================================
  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Start full dev environment (infra + migrate + backend + frontend + api watch)
    cmds:
      - task: infra:up
      - task: db:migrate
      - defer: { task: infra:down }
      - task: generate:api
      - task: _dev:services

  dev:backend:
    desc: Start infra + backend only (no frontend)
    cmds:
      - task: infra:up
      - task: db:migrate
      - task: _backend:dev

  dev:frontend:
    desc: Start frontend only (assumes backend is running)
    cmds:
      - task: _frontend:dev

  # =============================================================================
  # Infrastructure
  # =============================================================================
  infra:up:
    desc: Start infrastructure (PostgreSQL, Redis, MinIO, MailHog)
    cmds:
      - docker compose up -d
      - task: _infra:wait

  infra:down:
    desc: Stop infrastructure
    cmds:
      - docker compose down

  infra:destroy:
    desc: Stop infrastructure and delete all volumes
    prompt: This will delete all data. Are you sure?
    cmds:
      - docker compose down -v

  infra:logs:
    desc: View infrastructure logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  # =============================================================================
  # Code Generation
  # =============================================================================
  generate:
    desc: Generate all (API types + sqlc + mocks)
    cmds:
      - task: generate:api
      - task: generate:sqlc
      - task: generate:mocks

  generate:api:
    desc: Generate OpenAPI spec and TypeScript types
    sources:
      - "{{.BACKEND_DIR}}/internal/interface/**/*.go"
    generates:
      - "{{.FRONTEND_DIR}}/src/lib/api/schema.d.ts"
    cmds:
      - task: _generate:api:swag
      - task: _generate:api:types

  generate:sqlc:
    desc: Generate Go code from SQL queries
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - sqlc generate

  generate:mocks:
    desc: Generate mocks via go generate
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go generate ./...

  # =============================================================================
  # Database
  # =============================================================================
  db:migrate:
    desc: Apply all pending migrations
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" up

  db:rollback:
    desc: Rollback the last migration
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" down 1

  db:reset:
    desc: Drop + recreate + migrate database
    prompt: This will delete all data. Are you sure?
    cmds:
      - docker compose exec -T postgres psql -U postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'gc_storage' AND pid <> pg_backend_pid();" || true
      - docker compose exec -T postgres psql -U postgres -c "DROP DATABASE IF EXISTS gc_storage;"
      - docker compose exec -T postgres psql -U postgres -c "CREATE DATABASE gc_storage;"
      - task: db:migrate

  db:create-migration:
    desc: "Create a new migration (usage: task db:create-migration NAME=xxx)"
    cmds:
      - |
        if [ -z "{{.NAME}}" ]; then
          echo "Usage: task db:create-migration NAME=migration_name"
          exit 1
        fi
        migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.NAME}}

  db:connect:
    desc: Connect to PostgreSQL via psql
    cmds:
      - docker compose exec postgres psql -U postgres -d gc_storage

  db:version:
    desc: Show current migration version
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "$DATABASE_URL" version

  # =============================================================================
  # Testing
  # =============================================================================
  test:
    desc: Run all unit tests (backend + frontend)
    cmds:
      - task: _test:backend
      - task: _test:frontend

  test:integration:
    desc: Run integration tests (starts infra if needed)
    cmds:
      - task: infra:up
      - task: _db:setup-test
      - task: _test:integration:run

  test:coverage:
    desc: Run tests with coverage reports
    cmds:
      - task: _test:coverage:backend
      - task: _test:coverage:frontend

  # =============================================================================
  # Code Quality
  # =============================================================================
  check:
    desc: Lint + test (quick validation before commit)
    cmds:
      - task: lint
      - task: test

  lint:
    desc: Run all linters
    cmds:
      - task: _lint:backend
      - task: _lint:frontend

  fmt:
    desc: Format all code
    cmds:
      - task: _fmt:backend
      - task: _fmt:frontend

  # =============================================================================
  # Build
  # =============================================================================
  build:
    desc: Build backend + frontend for production
    cmds:
      - task: _build:backend
      - task: _build:frontend

  # =============================================================================
  # CI
  # =============================================================================
  ci:
    desc: Full CI pipeline (lint + test + integration + build)
    cmds:
      - task: lint
      - task: test
      - task: test:integration
      - task: build

  # =============================================================================
  # Setup
  # =============================================================================
  setup:
    desc: Install all tools and dependencies
    cmds:
      - task: setup:tools
      - cd {{.BACKEND_DIR}} && go mod tidy
      - cd {{.FRONTEND_DIR}} && pnpm install
      - task: setup:hooks

  setup:tools:
    desc: Install required Go development tools
    cmds:
      - |
        echo "Installing Go tools..."
        go install github.com/air-verse/air@latest
        go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/swaggo/swag/cmd/swag@latest
        go install github.com/evilmartians/lefthook@latest
        echo "All tools installed!"
      - task: setup:hooks

  setup:hooks:
    desc: Install git pre-commit hooks (lefthook)
    cmds:
      - lefthook install

  doctor:
    desc: Check if all required tools are installed
    cmds:
      - |
        echo "Checking required tools..."
        echo ""
        MISSING=""
        check() {
          if command -v "$1" &> /dev/null; then
            echo "  ok  $1"
          else
            echo "  NG  $1 - not found"
            MISSING="$MISSING $1"
          fi
        }
        check go
        check node
        check pnpm
        check docker
        check air
        check sqlc
        check migrate
        check golangci-lint
        check swag
        check lefthook
        echo ""
        if [ -z "$MISSING" ]; then
          echo "All tools are installed!"
        else
          echo "Missing:$MISSING"
          echo "Run 'task setup:tools' to install Go tools"
          exit 1
        fi

  clean:
    desc: Clean build artifacts and caches
    cmds:
      - rm -rf {{.BACKEND_DIR}}/bin {{.BACKEND_DIR}}/tmp {{.BACKEND_DIR}}/coverage.*
      - rm -rf {{.FRONTEND_DIR}}/dist {{.FRONTEND_DIR}}/coverage

  # =============================================================================
  # Internal tasks (not shown in task --list)
  # =============================================================================
  _dev:services:
    internal: true
    deps:
      - _backend:dev
      - _frontend:dev
      - _generate:api:watch

  _backend:dev:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - air

  _frontend:dev:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm dev

  _generate:api:swag:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - swag init -g cmd/api/main.go -o docs --parseDependency --parseInternal

  _generate:api:types:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm exec swagger2openapi ../backend/docs/swagger.json -o src/lib/api/openapi.json
      - pnpm exec openapi-typescript src/lib/api/openapi.json -o src/lib/api/schema.d.ts

  _generate:api:watch:
    internal: true
    cmds:
      - task --watch generate:api

  _infra:wait:
    internal: true
    cmds:
      - |
        echo "Waiting for services..."
        until docker compose exec -T postgres pg_isready -U postgres > /dev/null 2>&1; do sleep 1; done
        until docker compose exec -T redis redis-cli ping > /dev/null 2>&1; do sleep 1; done
        until curl -sf http://localhost:9000/minio/health/live > /dev/null 2>&1; do sleep 1; done
        echo "All services ready!"

  _db:setup-test:
    internal: true
    cmds:
      - docker compose exec -T postgres psql -U postgres -c "CREATE DATABASE gc_storage_test;" 2>/dev/null || true
      - migrate -path {{.MIGRATIONS_DIR}} -database "postgres://postgres:postgres@localhost:5432/gc_storage_test?sslmode=disable" up

  # ---- Test ----
  _test:backend:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test ./internal/...

  _test:frontend:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm test

  _test:integration:run:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    env:
      INTEGRATION_TEST: "true"
    cmds:
      - go test -v -count=1 ./tests/integration/...

  _test:coverage:backend:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test -coverprofile=coverage.out ./internal/... && go tool cover -html=coverage.out -o coverage.html

  _test:coverage:frontend:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm test:coverage

  # ---- Lint / Fmt ----
  _lint:backend:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - golangci-lint run ./...

  _lint:frontend:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm lint

  _fmt:backend:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    ignore_error: true
    cmds:
      - go fmt ./... && goimports -w .

  _fmt:frontend:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm format

  # ---- Build ----
  _build:backend:
    internal: true
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o bin/api cmd/api/main.go

  _build:frontend:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build
